---
- name: Setup MacOS
  hosts: localhost
  become: false
  vars:
  pre_tasks:
    - name: Check Homebrew is installed
      stat:
        path: /opt/homebrew/bin/brew
      register: homebrew_check
    - name: Fail if Homebrew is not installed
      fail:
        msg: Homebrew is missing...Install from http://brew.sh/
      when: not homebrew_check.stat.exists
    - name: Developer dir exists
      stat:
        path: ~/Developer
      register: developer_dir
    - name: create Developer dir
      shell: mkdir ~/Developer
      when: developer_dir.stat.exists == false
    - name: has oh-my-zsh
      stat:
        path: ~/.oh-my-zsh
      register: has_oh_my_zsh
  tasks:
    - name: install oh-my-zsh
      shell: curl -L https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh | sh
      when: has_oh_my_zsh.stat.exists == false
    - name: install vim-plug
      shell: curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    - name: nvm
      shell: >
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
      args:
        creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
    - include_tasks: tasks/brew.yml
    - include_tasks: tasks/git.yml
  post_tasks:
    - name: .dotfiles exists
      stat:
        path: "{{ ansible_env.HOME }}/.dotfiles"
      register: dotfiles_check
    - name: stow .dotfiles
      shell: stow -t $HOME -d $HOME/.dotfiles .
      when: dotfiles_check.stat.exists
