---
- name: Setup MacOS
  hosts: localhost
  become: false
  vars:
  pre_tasks:
    - include_tasks: tasks/homebrew-exists.yml
    - include_tasks: tasks/ohmyzsh-install.yml
    - name: Developer dir exists
      stat:
        path: ~/Developer
      register: developer_dir
    - name: create Developer dir
      shell: mkdir ~/Developer
      when: developer_dir.stat.exists == false
    - name: Packer dir
      stat:
        path: $HOME/.local/share/nvim/site/pack/packer/start/packer.nvim
      register: packer_dir
  tasks:
    - name: install vim-plug
      shell: curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    - name: install vim-plug (nvim)
      shell: curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    - name: install packer
      shell: git clone --depth 1 https://github.com/wbthomason/packer.nvim $HOME/.local/share/nvim/site/pack/packer/start/packer.nvim
      when: packer_dir.stat.exists == false
    - name: nvm
      shell: >
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
      args:
        creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
    - include_tasks: tasks/brew-dev-env.yml
    - include_tasks: tasks/git.yml
    - include_tasks: tasks/go.yml
  post_tasks:
    - name: .dotfiles exists
      stat:
        path: "{{ ansible_env.HOME }}/.dotfiles"
      register: dotfiles_check
    - name: stow .dotfiles
      shell: stow -t $HOME -d $HOME/.dotfiles .
      when: dotfiles_check.stat.exists

