---
- name: Setup MacOS
  hosts: localhost
  become: false
  vars:
  pre_tasks:
    - include_tasks: tasks/require-homebrew.yml
    - include_tasks: tasks/ohmyzsh-install.yml
    - name: Developer dir exists
      stat:
        path: ~/Developer
      register: developer_dir
    - name: create Developer dir
      shell: mkdir ~/Developer
      when: developer_dir.stat.exists == false
  tasks:
    - include_tasks: tasks/brew-dev-env.yml
    - include_tasks: tasks/git.yml
    - include_tasks: tasks/ruby-gems.yml
  post_tasks:
    - name: .dotfiles exists
      stat:
        path: "{{ ansible_env.HOME }}/.dotfiles"
      register: dotfiles_check
    - name: stow .dotfiles
      shell: stow -t $HOME -d $HOME/.dotfiles .
      when: dotfiles_check.stat.exists

