    brew_cask_packages:
      - pop
      - zoom
      - slack
      - atom
      - docker
      - firefox
      - google-chrome
      - slack
      - spotify
      - visual-studio-code
      - intellij-idea
    brew_packages:
      - tmux
      - fzf
      - stow
      - docker-compose
      - git
      - jq
      - pyenv
      - python
      - rbenv
      - tree
      - wget
      - figlet
      - yarn
      - openjdk@11

