    - name: Installing Homebrew Cask Packages
      homebrew_cask:
        name:
        - pop
        - zoom
        - slack
        - atom
        - docker
        - firefox
        - google-chrome
        - slack
        - spotify
        - visual-studio-code
        - intellij-idea
        state: present
      register: result
      until: result is successful
      when: homebrew_check.stat.exists

    - name: Installing Homebrew Packages
      homebrew:
        name:
        - tmux
        - fzf
        - stow
        - docker-compose
        - git
        - jq
        - pyenv
        - python
        - rbenv
        - tree
        - wget
        - figlet
        - yarn
        - neovim
        state: present
      register: result
      until: result is successful
      when: homebrew_check.stat.exists
