    - name: Check Homebrew is installed
      stat:
        path: /opt/homebrew/bin/brew
      register: homebrew_check
      
    - name: Fail if Homebrew is not installed
      fail:
        msg: Homebrew is missing...Install from http://brew.sh/
      when: not homebrew_check.stat.exists

    - name: Updating Homebrew
      homebrew:
        update_homebrew: true
      when: homebrew_check.stat.exists

    - name: Upgrading Homebrew Packages
      homebrew:
        upgrade_all: true
      register: result
      until: result is successful
      when: homebrew_check.stat.exists

